title: (A)MAR
email: amarpeladiversidade@gmail.com
description: (A)MAR - Açores pela Diversidade é o primeiro centro de apoio à população LGBTI (Lésbicas, Gays, Bissexuais, Trans e Intersexo) da Região Autónoma dos Açores.
url: "https://amarpeladiversidade.pt" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
permalink: pretty 
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
