---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Páginas
- type: document
  path: comunicacao.html
  label: Comunicação Social
- type: document
  path: index.html
  label: Sobre
- type: document
  path: quem-somos.html
  label: Quem Somos
- type: document
  path: servicos.html
  label: Serviços
- type: document
  path: atividades.html
  label: Atividades
- type: document
  path: rede.html
  label: Rede
- type: document
  path: contactos.html
  label: Contactos
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
